/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GameState = { 'winner' : null } |
  { 'voting' : null } |
  { 'results' : null } |
  { 'lobby' : null } |
  { 'roleReveal' : null } |
  { 'drawing' : null };
export interface Player {
  'id' : PlayerId,
  'name' : string,
  'isHost' : boolean,
  'eliminated' : boolean,
  'isSpy' : boolean,
}
export type PlayerId = number;
export interface Room {
  'turnOrder' : Uint32Array,
  'started' : boolean,
  'votes' : Array<[PlayerId, PlayerId]>,
  'code' : RoomCode,
  'host' : PlayerId,
  'drawings' : Array<Stroke>,
  'state' : GameState,
  'currentWord' : Word,
  'players' : Array<Player>,
}
export type RoomCode = string;
export interface Stroke {
  'color' : string,
  'width' : bigint,
  'points' : Array<[number, number]>,
}
export type Word = string;
export interface _SERVICE {
  'createRoom' : ActorMethod<[string, string], string>,
  'getRoomState' : ActorMethod<[string], Room>,
  'joinRoom' : ActorMethod<[string, string], boolean>,
  'startGame' : ActorMethod<[string, PlayerId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];