/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerId = IDL.Nat32;
export const RoomCode = IDL.Text;
export const Stroke = IDL.Record({
  'color' : IDL.Text,
  'width' : IDL.Nat,
  'points' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
});
export const GameState = IDL.Variant({
  'winner' : IDL.Null,
  'voting' : IDL.Null,
  'results' : IDL.Null,
  'lobby' : IDL.Null,
  'roleReveal' : IDL.Null,
  'drawing' : IDL.Null,
});
export const Word = IDL.Text;
export const Player = IDL.Record({
  'id' : PlayerId,
  'name' : IDL.Text,
  'isHost' : IDL.Bool,
  'eliminated' : IDL.Bool,
  'isSpy' : IDL.Bool,
});
export const Room = IDL.Record({
  'turnOrder' : IDL.Vec(PlayerId),
  'started' : IDL.Bool,
  'votes' : IDL.Vec(IDL.Tuple(PlayerId, PlayerId)),
  'code' : RoomCode,
  'host' : PlayerId,
  'drawings' : IDL.Vec(Stroke),
  'state' : GameState,
  'currentWord' : Word,
  'players' : IDL.Vec(Player),
});

export const idlService = IDL.Service({
  'createRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getRoomState' : IDL.Func([IDL.Text], [Room], ['query']),
  'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'startGame' : IDL.Func([IDL.Text, PlayerId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerId = IDL.Nat32;
  const RoomCode = IDL.Text;
  const Stroke = IDL.Record({
    'color' : IDL.Text,
    'width' : IDL.Nat,
    'points' : IDL.Vec(IDL.Tuple(IDL.Float64, IDL.Float64)),
  });
  const GameState = IDL.Variant({
    'winner' : IDL.Null,
    'voting' : IDL.Null,
    'results' : IDL.Null,
    'lobby' : IDL.Null,
    'roleReveal' : IDL.Null,
    'drawing' : IDL.Null,
  });
  const Word = IDL.Text;
  const Player = IDL.Record({
    'id' : PlayerId,
    'name' : IDL.Text,
    'isHost' : IDL.Bool,
    'eliminated' : IDL.Bool,
    'isSpy' : IDL.Bool,
  });
  const Room = IDL.Record({
    'turnOrder' : IDL.Vec(PlayerId),
    'started' : IDL.Bool,
    'votes' : IDL.Vec(IDL.Tuple(PlayerId, PlayerId)),
    'code' : RoomCode,
    'host' : PlayerId,
    'drawings' : IDL.Vec(Stroke),
    'state' : GameState,
    'currentWord' : Word,
    'players' : IDL.Vec(Player),
  });
  
  return IDL.Service({
    'createRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getRoomState' : IDL.Func([IDL.Text], [Room], ['query']),
    'joinRoom' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'startGame' : IDL.Func([IDL.Text, PlayerId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };