/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PlayerId = number;
export interface Player {
    id: PlayerId;
    name: string;
    isHost: boolean;
    eliminated: boolean;
    isSpy: boolean;
}
export interface Stroke {
    color: string;
    width: bigint;
    points: Array<[number, number]>;
}
export type RoomCode = string;
export interface Room {
    turnOrder: Uint32Array;
    started: boolean;
    votes: Array<[PlayerId, PlayerId]>;
    code: RoomCode;
    host: PlayerId;
    drawings: Array<Stroke>;
    state: GameState;
    currentWord: Word;
    players: Array<Player>;
}
export type Word = string;
export enum GameState {
    winner = "winner",
    voting = "voting",
    results = "results",
    lobby = "lobby",
    roleReveal = "roleReveal",
    drawing = "drawing"
}
export interface backendInterface {
    createRoom(playerName: string, code: string): Promise<string>;
    getRoomState(roomCode: string): Promise<Room>;
    joinRoom(roomCode: string, playerName: string): Promise<boolean>;
    startGame(roomCode: string, hostPlayerId: PlayerId): Promise<void>;
}
import type { GameState as _GameState, Player as _Player, PlayerId as _PlayerId, Room as _Room, RoomCode as _RoomCode, Stroke as _Stroke, Word as _Word } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createRoom(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0, arg1);
            return result;
        }
    }
    async getRoomState(arg0: string): Promise<Room> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomState(arg0);
                return from_candid_Room_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomState(arg0);
            return from_candid_Room_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async joinRoom(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0, arg1);
            return result;
        }
    }
    async startGame(arg0: string, arg1: PlayerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startGame(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startGame(arg0, arg1);
            return result;
        }
    }
}
function from_candid_GameState_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Room_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Room {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    turnOrder: Uint32Array;
    started: boolean;
    votes: Array<[_PlayerId, _PlayerId]>;
    code: _RoomCode;
    host: _PlayerId;
    drawings: Array<_Stroke>;
    state: _GameState;
    currentWord: _Word;
    players: Array<_Player>;
}): {
    turnOrder: Uint32Array;
    started: boolean;
    votes: Array<[PlayerId, PlayerId]>;
    code: RoomCode;
    host: PlayerId;
    drawings: Array<Stroke>;
    state: GameState;
    currentWord: Word;
    players: Array<Player>;
} {
    return {
        turnOrder: value.turnOrder,
        started: value.started,
        votes: value.votes,
        code: value.code,
        host: value.host,
        drawings: value.drawings,
        state: from_candid_GameState_n3(_uploadFile, _downloadFile, value.state),
        currentWord: value.currentWord,
        players: value.players
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    winner: null;
} | {
    voting: null;
} | {
    results: null;
} | {
    lobby: null;
} | {
    roleReveal: null;
} | {
    drawing: null;
}): GameState {
    return "winner" in value ? GameState.winner : "voting" in value ? GameState.voting : "results" in value ? GameState.results : "lobby" in value ? GameState.lobby : "roleReveal" in value ? GameState.roleReveal : "drawing" in value ? GameState.drawing : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
